name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    environment: Renovate
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.2.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          repository: antispam2002/renovate-docker-utf-8-with-bom            
