name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.2.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
            
